
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: nation_avg_balance
    description: "This model calculates the average balance per nation"
    columns:
    - name: nation
    - name: average_balance

sources:
- name: tpch
  database: tpch
  schema: main
  tables:
  - name: customer
  - name: nation
