testproject:
  target: prod
  outputs:
    dev:
      type: duckdb
      path: /tmp/dev.duckdb
      threads: 2
      attach:
      - path: /tmp/tpch.duckdb

    prod:
      type: duckdb
      path: /tmp/prod.duckdb
      threads: 4
      attach:
      - path: /tmp/tpch.duckdb
